spring:
  datasource:
    url: jdbc:mysql://${MALL_DB_HOST}:3306/smallrain_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${MALL_DB_USER}
    password: ${MALL_DB_PASSWORD}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid1314159

logging:
  path: /var/logs #配置日志生成路径